@backend_HostAddress = http://localhost:5036

GET {{backend_HostAddress}}/api/authors
Accept: application/json

###

GET {{backend_HostAddress}}/api/genres
Accept: application/json

###

GET {{backend_HostAddress}}/api/books?search=test&authorId=1&genreId=1
Accept: application/json

###
